[package]
org = "ballerina"
name = "parse_string_array_types_tests"
version = "0.1.1"

[[dependency]]
org = "ballerina"
name = "csv_commons"
repository = "local"
version = "0.1.1"

[platform.java21]
graalvmCompatible = true

[build-options]
graalvmBuildOptions = "-H:+IncludeAllLocales"
