[package]
org = "wso2"
name = "csv_parse_stream"
version = "0.0.1"

[build-options]
observabilityIncluded = false
cloud = "k8s"

[[dependency]]
org = "ballerina"
name = "data.csv"
version = "0.1.0"
repository="local"