[package]
org = "ballerina"
name = "user_config_tests"
version = "0.1.0"

[[dependency]]
org = "ballerina"
name = "csv_commons"
repository = "local"
version = "0.1.0"

[platform.java17]
graalvmCompatible = true
