[package]
org = "ballerina"
name = "user_config_tests"
version = "0.7.1"

[[dependency]]
org = "ballerina"
name = "csv_commons"
repository = "local"
version = "0.7.1"

[platform.java21]
graalvmCompatible = true

[build-options]
graalvmBuildOptions = "-H:+IncludeAllLocales"
